### ISSUE TITLE
Unable to cast object of type 'System.IO.FileSystemEventArgs' to type 'System.IO.RenamedEventArgs'

### ISSUE THREAD

**Issue by remcoros** [Microsoft/VSProjectSystem#278]
Situation:

I have a web project (SDK style .csproj) with an 'App_Data' folder (excluded or included doesn't make any difference).

When A LOT of files and directories are created within App_Data (outside of VS), the following error occurs and is shown in a regular message box within Visual Studio:

```
---------------------------
Microsoft Visual Studio
---------------------------
The project system has encountered an error.

 

Unable to cast object of type 'System.IO.FileSystemEventArgs' to type 'System.IO.RenamedEventArgs'.



A diagnostic log has been written to the following location: "C:\Users\rro\AppData\Local\Temp\VsProjectFault_16b18749-4a32-4af1-9f21-11dba4cd2b6a.failure.txt".


---------------------------
OK   
---------------------------
```

This is the log file:

```
=====================
10-7-2018 12:10:09
Recoverable
System.AggregateException: One or more errors occurred. ---> System.InvalidCastException: Unable to cast object of type 'System.IO.FileSystemEventArgs' to type 'System.IO.RenamedEventArgs'.
   at Microsoft.VisualStudio.ProjectSystem.Designers.CoreDirectoryTreeProvider.<ProcessFileSystemEventAsync>d__72.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.Designers.CoreDirectoryTreeProvider.<ProcessFileEventsAsync>d__71.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.ProjectTreeProviderBase.TreeUpdateSubmission.<UpdateTree>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.VisualStudio.ProjectSystem.CoreProjectTreeProviderBase.<>c__DisplayClass69_1.<<Initialize>b__2>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.CoreProjectTreeProviderBase.<>c__DisplayClass71_0.<<SubmitTreeUpdateCoreAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.Designers.CoreDirectoryTreeProvider.<>c__DisplayClass69_1.<<ResetFileEventsQueueProcessor>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.InvalidCastException: Unable to cast object of type 'System.IO.FileSystemEventArgs' to type 'System.IO.RenamedEventArgs'.
   at Microsoft.VisualStudio.ProjectSystem.Designers.CoreDirectoryTreeProvider.<ProcessFileSystemEventAsync>d__72.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.Designers.CoreDirectoryTreeProvider.<ProcessFileEventsAsync>d__71.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.ProjectTreeProviderBase.TreeUpdateSubmission.<UpdateTree>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.VisualStudio.ProjectSystem.CoreProjectTreeProviderBase.<>c__DisplayClass69_1.<<Initialize>b__2>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.CoreProjectTreeProviderBase.<>c__DisplayClass71_0.<<SubmitTreeUpdateCoreAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.Designers.CoreDirectoryTreeProvider.<>c__DisplayClass69_1.<<ResetFileEventsQueueProcessor>b__0>d.MoveNext()<---
```

In our project this happens because hundreds of files and subdirectories are created within App_Data due to a 'nuget restore'. 

Note: this is not a 'nuget restore' for the VS project, it's part of a different (plugin) system, it just creates a lot of files.

The issue here is probably within the VS Project system / FilesystemWatcher that can't handle a lot of files/directories created at the same time.

**Comment by jviau** [comment]
Thanks for the report, we believe this issue to be fixed in d15.8 preview. If you still see it let us know! In the future, it is recommended to use https://developercommunity.visualstudio.com for reporting issues with VS.
